import type { Metadata } from 'next';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { EB_Garamond, Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import Providers from '@/providers/react-query';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const ebGaramond = EB_Garamond({
  subsets: ['latin'],
  variable: '--font-heading',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(inter.variable, ebGaramond.variable, 'antialiased min-h-[calc(100vh-1px)] flex flex-col')}>
        <main className='relative flex-1 flex flex-col'>
          <Providers>
            <ClerkProvider>{children}</ClerkProvider>
          </Providers>
        </main>
      </body>
    </html>
  );
}
